language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
  directories:
    - node_modules
    - test/node_modules
notifications:
  email: false
node_js:
  - "10"
  - "8"
